name: asdfgh
description: A new Flutter application.
version: 1.0.0+0

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  retrofit: 1.3.4
  logger: 0.9.2
  rflutter_alert: 1.0.3
  http: 0.12.0+4
  intl: 0.16.1
  json_annotation: 3.0.1
  flutter_bloc: 6.0.1
  pretty_dio_logger: 1.1.1
  freezed_annotation: 0.12.0
  flutter_progress_dialog: 0.1.0
  loading:
    git:
      url: git://github.com/leonzone/loading.git
      path: loading
      ref: 8f5a63f

dev_dependencies:
  retrofit_generator: 1.3.7+5
  build_runner: 1.10.2
  json_serializable: 3.4.0
  freezed: 0.12.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
